---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.12-stretch'

inputs:
  - name: src

run:
  path: sh
  args:
    - -c
    - |
      #!/bin/sh
      cd src
      go test
